import Head from "next/head";
import { Josefin_Sans } from "next/font/google";
import clsx from "clsx";

const Josefin = Josefin_Sans({ subsets: ["latin"], variable: "--josefin" });

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>The Interns</title>
        <meta name="description" content="Generated by The Interns" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="flex flex-col justify-center items-start w-full h-full relative gap-10 bg-[#ecf2f7]">
        <div className="flex justify-center items-center flex-grow-0 flex-shrink-0 w-full h-[75px] absolute left-0 top-0 overflow-hidden gap-2.5 px-[5px] py-4 bg-neutral-100 border-t-0 border-r-0 border-b-[5px] border-l-0 border-[#c0c9ee]">
          <p className="flex-grow-0 flex-shrink-0 text-xl text-center text-black max-w-full ml-60">
            Welcome to tDSP
          </p>
        </div>
        <div
          className={clsx(
            Josefin.className,
            "flex flex-col justify-start items-end flex-grow-0 flex-shrink-0 h-full w-[257px] absolute left-0 top-0 gap-[17px] py-[39px] bg-[#18202c]"
          )}
        >
          <button className="flex-grow-0 flex-shrink-0 w-[257px] h-[49px] text-4xl text-center text-[#3193f5] mb-10">
            The Interns
          </button>
          <button className="flex-grow-0 flex-shrink-0 w-[257px] h-10 text-xl font-medium text-left px-10 text-[#ecf2f7] hover:bg-[#253347] duration-200">
            Bid Request
          </button>
          <button className="flex-grow-0 flex-shrink-0 w-[257px] h-10 text-xl font-medium text-left px-10 text-[#ecf2f7] hover:bg-[#253347] duration-200">
            Bid Response
          </button>
          <button className="flex-grow-0 flex-shrink-0 w-[257px] h-10 text-xl font-medium text-left px-10 text-[#ecf2f7] hover:bg-[#253347] duration-200">
            Creative
          </button>
          <button className="flex-grow-0 flex-shrink-0 w-[257px] h-10 text-xl font-medium text-left px-10 text-[#ecf2f7] hover:bg-[#253347] duration-200">
            Campaign
          </button>
          <button className="flex-grow-0 flex-shrink-0 w-[257px] h-10 text-xl font-medium text-left px-10 text-[#ecf2f7] hover:bg-[#253347] duration-200">
            Category
          </button>
          <button className="flex-grow-0 flex-shrink-0 w-[257px] h-10 text-xl font-medium text-left px-10 text-[#ecf2f7] hover:bg-[#253347] duration-200">
            Configuration
          </button>
          <button className="flex-grow-0 flex-shrink-0 w-[257px] h-10 text-xl font-medium text-left px-10 text-[#ecf2f7] hover:bg-[#253347] duration-200">
            Notification
          </button>
          <button className="flex-grow-0 flex-shrink-0 w-[257px] h-10 text-xl font-medium text-center text-[#ecf2f7] mt-auto hover:bg-[#253347] duration-200">
            Logout
          </button>
        </div>
      </div>
    </>
  );
}
