import Head from "next/head";
import { Josefin_Sans } from "next/font/google";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import axios from "axios";
import { useQueryClient } from "react-query";
import DashboardAdops from "@/components/dashboardadops";
const Josefin = Josefin_Sans({ subsets: ["latin"], variable: "--josefin" });

export default function AdOps() {
  const router = useRouter();
  const [minBid, setMinBid] = useState<number>();
  const queryClient = useQueryClient();

  function getCookie(name: string) {
    const cookieValue = document.cookie.match(
      `(^|;)\\s*${name}\\s*=\\s*([^;]+)`
    );
    return cookieValue ? cookieValue.pop() : "";
  }

  useEffect(() => {
    if (getCookie("token") === "") {
      router.push("/login");
    }
  }, []);

  const handleBidChange = async (newMinBid: number) => {
    const token = getCookie("token");
    await axios.patch(
      `http://${process.env.NEXT_PUBLIC_HOST}/api/campaigns/`,
      {
        min_bid: newMinBid,
      },
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );

    queryClient.invalidateQueries("campaign");
    setMinBid(newMinBid);
  };

  return (
    <>
      <Head>
        <title>The Interns</title>
        <meta name="description" content="Generated by The Interns" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <DashboardAdops />
      <div className="flex flex-col w-full h-full relative bg-[#ecf2f7] pl-60">
        <div className="flex justify-center items-center flex-grow-0 flex-shrink-0 w-full h-[75px] overflow-hidden gap-2.5 px-[5px] py-4 bg-neutral-100 border-t-0 border-r-0 border-b-[5px] border-l-0 border-[#c0c9ee]">
          <p className="flex-grow-0 flex-shrink-0 text-xl text-center text-black max-w-full">
            Welcome to AdOps tDSP
          </p>
        </div>
        <div className="flex flex-col overflow-y-scroll">
          <div className="flex flex-col justify-start items-center flex-grow-0 flex-shrink-0 h-[693px] w-full gap-2.5 px-2.5 py-[70px]">
            <div className="flex flex-col justify-start items-center flex-grow-0 flex-shrink-0 h-[300px] w-[440px] relative overflow-hidden gap-[60px] bg-white border-2 border-[#3193f5]">
              <div className="self-stretch flex-grow-0 flex-shrink-0 h-11 relative overflow-hidden bg-[#e6e5e5] border-t-0 border-r-0 border-b border-l-0 border-[#3193f5]">
                <p className="w-[423px] h-11 absolute left-2 top-0 text-2xl font-medium text-center text-black">
                  Edit Minimal Bid For All Campaigns
                </p>
              </div>
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  const form = e.target as HTMLFormElement;
                  const [input] = form.children;
                  const { value } = input as HTMLInputElement;
                  handleBidChange(Number(value));
                }}
                className="flex-grow-0 flex-shrink-0 w-[187px] h-[41px] relative overflow-hidden"
              >
                <input
                  placeholder="0"
                  type={"number"}
                  defaultValue={minBid}
                  className="flex-grow-0 flex-shrink-0 w-[187px] h-[41px] text-center text-xl relative overflow-hidden bg-[#ecf2f7] border-2 border-[#3193f5]"
                />
              </form>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
